
import javax.swing.DefaultListModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Kisko
 */
public class VentanaPrincipal extends javax.swing.JFrame {

    
    private DefaultListModel modelonuevo;
    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal() {
        initComponents();
        
        
    }
        /**
         * Metodo para eliminar partido
         * @param numero_partido 
         */
        public void eliminarPartido(int numero_partido)
        {
            listaPartidos.remove(numero_partido);
        }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pTitulo = new javax.swing.JPanel();
        pTituloCentro = new javax.swing.JPanel();
        lPartido = new javax.swing.JLabel();
        lVacio = new javax.swing.JLabel();
        lResultado = new javax.swing.JLabel();
        pTituloNorte = new javax.swing.JPanel();
        lQuiniela = new javax.swing.JLabel();
        pCentro = new javax.swing.JPanel();
        pPartido = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listaPartidos = new javax.swing.JList<>();
        pBotones = new javax.swing.JPanel();
        bNuevo = new javax.swing.JButton();
        bEliminar = new javax.swing.JButton();
        bQuiniela = new javax.swing.JButton();
        bReset = new javax.swing.JButton();
        pResultado = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        listaResultados = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pTitulo.setLayout(new java.awt.BorderLayout());

        pTituloCentro.setLayout(new java.awt.GridLayout(1, 2));

        lPartido.setText("Partido");
        pTituloCentro.add(lPartido);
        pTituloCentro.add(lVacio);

        lResultado.setText("Resultado");
        pTituloCentro.add(lResultado);

        pTitulo.add(pTituloCentro, java.awt.BorderLayout.CENTER);

        lQuiniela.setFont(new java.awt.Font("Trebuchet MS", 0, 36)); // NOI18N
        lQuiniela.setForeground(new java.awt.Color(255, 0, 0));
        lQuiniela.setText("QUINIELA");
        pTituloNorte.add(lQuiniela);

        pTitulo.add(pTituloNorte, java.awt.BorderLayout.NORTH);

        getContentPane().add(pTitulo, java.awt.BorderLayout.NORTH);

        pCentro.setLayout(new java.awt.BorderLayout());

        pPartido.setLayout(new java.awt.GridLayout(1, 0));

        jScrollPane1.setViewportView(listaPartidos);

        pPartido.add(jScrollPane1);

        pCentro.add(pPartido, java.awt.BorderLayout.LINE_START);

        pBotones.setLayout(new java.awt.GridLayout(4, 0));

        bNuevo.setText("Nuevo");
        bNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bNuevoActionPerformed(evt);
            }
        });
        pBotones.add(bNuevo);

        bEliminar.setText("Eliminar");
        bEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bEliminarActionPerformed(evt);
            }
        });
        pBotones.add(bEliminar);

        bQuiniela.setText("Realizar quiniela");
        pBotones.add(bQuiniela);

        bReset.setText("Resetear");
        bReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bResetActionPerformed(evt);
            }
        });
        pBotones.add(bReset);

        pCentro.add(pBotones, java.awt.BorderLayout.CENTER);

        pResultado.setLayout(new java.awt.GridLayout(1, 0));

        jScrollPane2.setViewportView(listaResultados);

        pResultado.add(jScrollPane2);

        pCentro.add(pResultado, java.awt.BorderLayout.EAST);

        getContentPane().add(pCentro, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents
/**
 * Boton Eliminar para eliminar un partido de la lista de los partidos.
 * @param evt 
 */
    private void bEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bEliminarActionPerformed
        // TODO add your handling code here:
        
        int numero_partido = 0;
        DefaultListModel modelo_quiniela = (DefaultListModel) listaPartidos.getModel();
        numero_partido = listaPartidos.getSelectedIndex();
        
        modelo_quiniela.remove(numero_partido);
        
    }//GEN-LAST:event_bEliminarActionPerformed

    private void bNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bNuevoActionPerformed

        
        
    }//GEN-LAST:event_bNuevoActionPerformed
/**
 * Boton Resetear para resetear un Resultado.
 * @param evt 
 */
    private void bResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bResetActionPerformed
        // TODO add your handling code here:
        
        DefaultListModel modelo_quiniela=new DefaultListModel();
        listaResultados.setModel(modelo_quiniela);
    }//GEN-LAST:event_bResetActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bEliminar;
    private javax.swing.JButton bNuevo;
    private javax.swing.JButton bQuiniela;
    private javax.swing.JButton bReset;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lPartido;
    private javax.swing.JLabel lQuiniela;
    private javax.swing.JLabel lResultado;
    private javax.swing.JLabel lVacio;
    private javax.swing.JList<String> listaPartidos;
    private javax.swing.JList<String> listaResultados;
    private javax.swing.JPanel pBotones;
    private javax.swing.JPanel pCentro;
    private javax.swing.JPanel pPartido;
    private javax.swing.JPanel pResultado;
    private javax.swing.JPanel pTitulo;
    private javax.swing.JPanel pTituloCentro;
    private javax.swing.JPanel pTituloNorte;
    // End of variables declaration//GEN-END:variables
}
